/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AboutImport } from './routes/about'
import { Route as BookIdRouteImport } from './routes/$bookId.route'
import { Route as IndexImport } from './routes/index'
import { Route as BookIdIndexImport } from './routes/$bookId.index'

// Create/Update Routes

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const BookIdRouteRoute = BookIdRouteImport.update({
  id: '/$bookId',
  path: '/$bookId',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const BookIdIndexRoute = BookIdIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BookIdRouteRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/$bookId': {
      id: '/$bookId'
      path: '/$bookId'
      fullPath: '/$bookId'
      preLoaderRoute: typeof BookIdRouteImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/$bookId/': {
      id: '/$bookId/'
      path: '/'
      fullPath: '/$bookId/'
      preLoaderRoute: typeof BookIdIndexImport
      parentRoute: typeof BookIdRouteImport
    }
  }
}

// Create and export the route tree

interface BookIdRouteRouteChildren {
  BookIdIndexRoute: typeof BookIdIndexRoute
}

const BookIdRouteRouteChildren: BookIdRouteRouteChildren = {
  BookIdIndexRoute: BookIdIndexRoute,
}

const BookIdRouteRouteWithChildren = BookIdRouteRoute._addFileChildren(
  BookIdRouteRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$bookId': typeof BookIdRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/$bookId/': typeof BookIdIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/$bookId': typeof BookIdIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/$bookId': typeof BookIdRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/$bookId/': typeof BookIdIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$bookId' | '/about' | '/$bookId/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/$bookId'
  id: '__root__' | '/' | '/$bookId' | '/about' | '/$bookId/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BookIdRouteRoute: typeof BookIdRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BookIdRouteRoute: BookIdRouteRouteWithChildren,
  AboutRoute: AboutRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/$bookId",
        "/about"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/$bookId": {
      "filePath": "$bookId.route.tsx",
      "children": [
        "/$bookId/"
      ]
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/$bookId/": {
      "filePath": "$bookId.index.tsx",
      "parent": "/$bookId"
    }
  }
}
ROUTE_MANIFEST_END */
